// Build design-pass/checker/checker.html: checker.src.html with check.js and
// rules/mmw_rules.json inlined, so the page is one self-contained file that
// can be pasted into WPP Open as embedded code (only JSZip comes from cdnjs).
//
// Usage:  node design-pass/checker/build_page.js   (after tools/build_rules.js)
const fs = require('fs'), path = require('path');
const D = __dirname, ROOT = path.join(D, '../..');
const rules = JSON.parse(fs.readFileSync(path.join(ROOT, 'rules/mmw_rules.json'), 'utf8'));
// The page does not need the layout geometry samples; keep it lean.
for (const L of Object.values(rules.layouts)) delete L.elements;
const js = fs.readFileSync(path.join(D, 'check.js'), 'utf8');
let html = fs.readFileSync(path.join(D, 'checker.src.html'), 'utf8')
  .replace('<!-- SOURCE. Build checker.html with: node design-pass/checker/build_page.js -->',
    '<!-- GENERATED by design-pass/checker/build_page.js from checker.src.html -- do not edit -->');
// Function replacers: the inlined text contains `$` sequences.
html = html.replace('/*CHECK_JS*/', () => js.replace(/<\/script/gi, '<\\/script'))
  .replace('/*RULES_JSON*/', () => JSON.stringify(rules).replace(/<\//g, '<\\/'));
fs.writeFileSync(path.join(D, 'checker.html'), html);
console.log('wrote design-pass/checker/checker.html (' + Math.round(html.length / 1024) + ' KB)');
