// Layout fingerprints for builder-made decks: run every layout in the QA deck
// (test-deck.html) through the real engine and record the boxes it produces,
// plus variants with fewer items for list/grid layouts. Builder slides carry
// no MMW layout name, so Design Pass identifies their layout by matching
// their shapes against these boxes. Text boxes also record which content
// field they hold, so copy budgets can be checked per field.
//
// Writes rules/fingerprints.json. Usage: node tools/build_fingerprints.js
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
global.window = { StandardDeck: { SD_CONST: { SLIDE_W: 13.33, SLIDE_H: 7.5, SAFE_X_MIN: 0.5, SAFE_Y_MIN: 0.75 } } };
console.warn = () => {}; console.error = () => {};
require(path.join(ROOT, 'deck-layouts.js'));
require(path.join(ROOT, 'map-data.js'));
require(path.join(ROOT, 'deck-maps.js'));
const DL = window.DeckLayouts;
const html = fs.readFileSync(path.join(ROOT, 'test-deck.html'), 'utf8');
const a = html.indexOf('var D=[') + 6, b = html.indexOf('\n];', a);
const D = JSON.parse(html.slice(a, b + 2));
const clone = (x) => JSON.parse(JSON.stringify(x));
const r2 = (v) => Math.round(v * 100) / 100;
const textOf = (e) => (e.paras ? e.paras.map((q) => (q.runs || []).map((r) => r.text || '').join('')).join(' ') : String(e.text || ''));
const norm = (p) => p.map((k) => (typeof k === 'number' ? '[]' : '.' + k)).join('').replace(/^\./, '').replace(/\.\[\]/g, '[]');

// Every string in the slide data, by normalised field path, to name text boxes.
function strings(v, p, out) {
  if (typeof v === 'string') { if (v.trim()) out.push({ path: norm(p), text: v }); return; }
  if (Array.isArray(v)) { v.forEach((x, i) => strings(x, p.concat(i), out)); return; }
  if (v && typeof v === 'object') for (const [k, x] of Object.entries(v)) if (k !== 'layout') strings(x, p.concat(k), out);
}
const squash = (s) => String(s).toUpperCase().replace(/\s+/g, ' ').trim();

function print(row) {
  let els;
  try { els = DL.dispatch(clone(row)) || []; } catch (e) { return null; }
  const S = []; strings(row, [], S);
  const boxes = [];
  for (const e of els) {
    if (e.x == null || e.y == null || e.w == null || e.h == null) continue;
    const t = e.type === 't';
    const box = [r2(+e.x), r2(+e.y), r2(+e.w), r2(+e.h), t ? 1 : 0];
    if (t) {
      const tx = squash(textOf(e));
      const hit = S.find((s) => squash(s.text) === tx) || S.find((s) => tx && squash(s.text).startsWith(tx.slice(0, 20)));
      if (hit) box.push(hit.path);
    }
    boxes.push(box);
  }
  return boxes;
}

// Variants: each array field shortened to every length down to 1, one at a time.
function variants(row) {
  const out = [row];
  for (const [k, v] of Object.entries(row)) {
    if (!Array.isArray(v) || v.length < 2 || typeof v[0] !== 'object') continue;
    for (let n = v.length - 1; n >= 1; n--) { const r = clone(row); r[k] = v.slice(0, n); out.push(r); }
  }
  return out;
}

const prints = [], seen = new Set();
for (const row of D) {
  // canvas* are free-form (the deck author draws them): nothing to match
  if (!DL.LAYOUT_MAP[row.layout] || /^canvas/.test(row.layout)) continue;
  for (const v of variants(row)) {
    const boxes = print(v);
    if (!boxes || !boxes.length) continue;
    const key = row.layout + JSON.stringify(boxes.map((x) => x.slice(0, 5)));
    if (seen.has(key)) continue;
    seen.add(key);
    // Cap each print: every text box plus the largest other shapes. The US
    // map alone is 19,000 state shapes; its text and frame identify it.
    const MAX = 60, text = boxes.filter((x) => x[4]), other = boxes.filter((x) => !x[4]).sort((p, q) => q[2] * q[3] - p[2] * p[3]);
    prints.push({ slug: row.layout, boxes: text.length >= MAX ? text : text.concat(other.slice(0, MAX - text.length)) });
  }
}
fs.writeFileSync(path.join(ROOT, 'rules/fingerprints.json'), JSON.stringify({
  _about: 'GENERATED by tools/build_fingerprints.js from test-deck.html through the engine (' + DL.VERSION + '). Box: [x, y, w, h, isText, field?] in engine inches.',
  engine: DL.VERSION, prints }) + '\n');
console.log('wrote rules/fingerprints.json: ' + prints.length + ' fingerprints for ' + new Set(prints.map((p) => p.slug)).size + ' layouts, ' +
  Math.round(fs.statSync(path.join(ROOT, 'rules/fingerprints.json')).size / 1024) + ' KB');
