#!/usr/bin/env python3
"""Build the Phosphor icon set (thin weight) into deck-icons.js as `ph-*` icons.

Phosphor (https://phosphoricons.com, MIT -- see licenses/phosphor-LICENSE.txt)
is the fallback set behind the 72 `mmw-*` brand icons: 1,512 single-subject
line icons. The thin weight is used because its stroke (8 on a 256 grid,
0.031 of the icon) matches the MMW set's (0.034) -- light and regular read
visibly heavier next to them.

Each icon keeps Phosphor's own geometry; the per-element stroke attributes
(identical on every element of a thin icon) move to the root <svg> with
stroke="currentColor" so DeckIcons.get() can recolour it. The eight fill-only
icons (dots, numpad, wifi-none) get fill="currentColor" on the root instead --
as shipped they have no colour and would always render black.

The result replaces the block between the BEGIN/END PHOSPHOR ICONS markers in
deck-icons.js (inserted after the MMW block on first run).

Usage:  python3 tools/build_phosphor_icons.py "<unzipped phosphor-icons>/SVGs/thin"
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BEGIN = '// ---- BEGIN PHOSPHOR ICONS (generated by tools/build_phosphor_icons.py; MIT, Phosphor Icons) ----'
END = '// ---- END PHOSPHOR ICONS ----'
COMMON = ' stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="8"'

def convert(svg):
    body = re.sub(r'<\?xml.*?\?>|<svg[^>]*>|</svg>|<rect width="256" height="256" fill="none"/>', '', svg, flags=re.S)
    if 'stroke=' in body:
        body = body.replace(COMMON, '').replace(' fill="none"', '')
        if 'stroke=' in body:
            raise ValueError('unexpected stroke attribute left')
        root = 'fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"'
    else:
        root = 'fill="currentColor"'
    body = re.sub(r'\s+', ' ', body).strip()
    assert "'" not in body and '<style' not in body and '<image' not in body and 'href' not in body
    # Stored compact: '~s' (stroke) or '~f' (fill) + the drawing. DeckIcons.get()
    # adds the shared <svg> wrapper -- repeating it 1,512 times was ~290 KB.
    return ('~s' if root.startswith('fill="none"') else '~f') + body

def main(src):
    entries = []
    for fn in sorted(os.listdir(src)):
        m = re.match(r'^(.+)-thin\.svg$', fn)
        if not m:
            continue
        entries.append("'ph-%s':'%s'," % (m.group(1), convert(open(os.path.join(src, fn), encoding='utf-8').read())))
    if len(entries) < 1000:
        sys.exit('expected the full thin set, found %d icons' % len(entries))
    block = '\n'.join([BEGIN] + entries + [END])

    p = os.path.join(ROOT, 'deck-icons.js')
    js = open(p, encoding='utf-8').read()
    if BEGIN in js:
        js = js[:js.index(BEGIN)] + block + js[js.index(END) + len(END):]
    else:
        anchor = '// ---- END MMW ICONS ----'
        i = js.index(anchor) + len(anchor)
        js = js[:i] + '\n' + block + js[i:]
    js = re.sub(r'\| \d+ icons \*/', '| %d icons */' % len(re.findall(r"^'[^']+':'(?:<svg|~[sf])", js, re.M)), js, count=1)
    open(p, 'w', encoding='utf-8').write(js)
    print('wrote %d Phosphor icons into deck-icons.js' % len(entries))

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
