#!/usr/bin/env python3
"""Build the MMW brand icon set into deck-icons.js.

Source: the MARKET ANALYSIS and CHARTS line icons shipped in the Keynote
template package (MMW_Keynote Template_7.30.26/Data/ -- files named
'Asset <n><FAMILY>-<id>.svg'). Names come from tools/mmw_icon_names.json.

Each icon is single-stroke line art (one CSS class: fill none, stroke
#262626). This rewrites it into the shape deck-icons.js uses for its
icons: inline attributes, stroke="currentColor" so DeckIcons.get() can
recolour it, a square viewBox (padded so strokes aren't clipped), and one
stroke weight across the whole set. IDs and Illustrator data-names are
dropped -- they're junk and would collide when icons are inlined.

The result replaces the block between the BEGIN/END MMW ICONS markers in
deck-icons.js (inserted before the closing of the icon table on first run).

Usage:  python3 tools/build_mmw_icons.py "<path to Keynote package>/Data"
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
STROKE_RATIO = 0.0339   # stroke width / icon size -- the source set's median
BEGIN, END = '// ---- BEGIN MMW ICONS (generated by tools/build_mmw_icons.py) ----', '// ---- END MMW ICONS ----'

def convert(svg):
    vb = [float(v) for v in re.search(r'viewBox="([^"]+)"', svg).group(1).split()]
    x, y, w, h = vb
    side = max(w, h)
    sw = STROKE_RATIO * side
    pad = sw / 2 + side * 0.02
    sx, sy = x - (side - w) / 2 - pad, y - (side - h) / 2 - pad
    size = side + 2 * pad
    body = re.sub(r'<\?xml.*?\?>|<defs>.*?</defs>|<svg[^>]*>|</svg>', '', svg, flags=re.S)
    body = re.sub(r'\s(?:id|data-name|class)="[^"]*"', '', body)
    body = re.sub(r'\s+', ' ', body).strip()
    assert "'" not in body and '<style' not in body and '<image' not in body
    def f(v): return ('%.2f' % v).rstrip('0').rstrip('.')
    return ('<svg class="mmw" xmlns="http://www.w3.org/2000/svg" viewBox="%s %s %s %s" fill="none" '
            'stroke="currentColor" stroke-width="%s" stroke-linecap="round" stroke-linejoin="round">%s</svg>'
            % (f(sx), f(sy), f(size), f(size), f(sw), body))

def main(src):
    names = {k: v for k, v in json.load(open(os.path.join(HERE, 'mmw_icon_names.json'))).items() if not k.startswith('_')}
    found = {}
    for fn in os.listdir(src):
        m = re.match(r'^Asset (\d+)(MARKET ANALYSIS|CHARTS)-\d+\.svg$', fn)
        if m: found['%s %s' % (m.group(2), m.group(1))] = os.path.join(src, fn)
    missing = [k for k in names if k not in found]
    if missing: sys.exit('missing source icons: %s' % missing)
    if len(set(names.values())) != len(names): sys.exit('duplicate icon names in mmw_icon_names.json')
    lines = [BEGIN]
    for key in sorted(names, key=lambda k: names[k]):
        lines.append("'%s':'%s'," % (names[key], convert(open(found[key], encoding='utf-8').read())))
    lines.append(END)
    block = '\n'.join(lines)

    p = os.path.join(ROOT, 'deck-icons.js')
    js = open(p, encoding='utf-8').read()
    if BEGIN in js:
        js = js[:js.index(BEGIN)] + block + js[js.index(END) + len(END):]
    else:
        i = js.index('\n};\nfunction get(')
        # JS object literals accept a trailing comma, and every generated entry
        # carries one.
        js = js[:i] + ('' if js[:i].rstrip().endswith(',') else ',') + '\n' + block + js[i:]
    js = re.sub(r'\| \d+ icons \*/', '| %d icons */' % (len(re.findall(r"^'[^']+':'(?:<svg|~[sf])", js, re.M))), js, count=1)
    open(p, 'w', encoding='utf-8').write(js)
    print('wrote %d MMW icons into deck-icons.js' % len(names))

if __name__ == '__main__':
    if len(sys.argv) != 2: sys.exit(__doc__)
    main(sys.argv[1])
