// Extract character advance widths from the brand fonts into
// rules/font_metrics.json, for the Design Pass text-fit check. Only widths
// (numbers) are stored -- no font data. Needs the fonts installed (macOS
// paths below; override with env FONT_DIRS=dir1:dir2).
//
// Usage:  node tools/font_metrics.js   (then node tools/build_rules.js)
const fs = require('fs'), path = require('path'), os = require('os');
const ROOT = path.join(__dirname, '..');
const DIRS = (process.env.FONT_DIRS || ['/System/Library/Fonts/Supplemental', '/Library/Fonts', path.join(os.homedir(), 'Library/Fonts')].join(':')).split(':');
const FACES = {   // face name as decks use it -> font file
  'Arial': 'Arial.ttf', 'Arial Bold': 'Arial Bold.ttf',
  'Mazda Type Bold': 'MazdaType-Bold.otf', 'Mazda Type': 'MazdaType-Regular.otf',
  'Mazda Type Regular': 'MazdaType-Regular.otf', 'Mazda Type Medium': 'MazdaType-Medium.otf'
};
// Characters measured: printable ASCII, Latin-1, common typographic marks.
const CODES = [];
for (let c = 32; c < 127; c++) CODES.push(c);
for (let c = 160; c < 256; c++) CODES.push(c);
[0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20AC, 0x2122].forEach((c) => CODES.push(c));

function parse(buf) {
  const tables = {}, n = buf.readUInt16BE(4);
  for (let i = 0; i < n; i++) {
    const o = 12 + i * 16;
    tables[buf.toString('ascii', o, o + 4)] = { off: buf.readUInt32BE(o + 8), len: buf.readUInt32BE(o + 12) };
  }
  const upm = buf.readUInt16BE(tables.head.off + 18);
  const nh = buf.readUInt16BE(tables.hhea.off + 34);
  const asc = buf.readInt16BE(tables.hhea.off + 4), desc = buf.readInt16BE(tables.hhea.off + 6), gap = buf.readInt16BE(tables.hhea.off + 8);
  const adv = (g) => buf.readUInt16BE(tables.hmtx.off + Math.min(g, nh - 1) * 4);
  // cmap: Windows Unicode BMP (3,1) format 4
  const cm = tables.cmap.off, nsub = buf.readUInt16BE(cm + 2);
  let sub = null;
  for (let i = 0; i < nsub; i++) {
    const pid = buf.readUInt16BE(cm + 4 + i * 8), eid = buf.readUInt16BE(cm + 6 + i * 8), off = buf.readUInt32BE(cm + 8 + i * 8);
    if (pid === 3 && eid === 1 && buf.readUInt16BE(cm + off) === 4) sub = cm + off;
  }
  if (!sub) throw new Error('no (3,1) format-4 cmap');
  const segX2 = buf.readUInt16BE(sub + 6), ends = sub + 14, starts = ends + segX2 + 2, deltas = starts + segX2, ros = deltas + segX2;
  function glyph(c) {
    for (let i = 0; i < segX2 / 2; i++) {
      if (buf.readUInt16BE(ends + i * 2) < c) continue;
      const st = buf.readUInt16BE(starts + i * 2);
      if (st > c) return 0;
      const d = buf.readInt16BE(deltas + i * 2), ro = buf.readUInt16BE(ros + i * 2);
      if (!ro) return (c + d) & 0xFFFF;
      const g = buf.readUInt16BE(ros + i * 2 + ro + (c - st) * 2);
      return g ? (g + d) & 0xFFFF : 0;
    }
    return 0;
  }
  const w = {};
  for (const c of CODES) { const g = glyph(c); if (g) w[c] = Math.round(adv(g) / upm * 1000); }
  return { line: +((asc - desc + gap) / upm).toFixed(4), w };
}

const out = { _about: 'GENERATED by tools/font_metrics.js: character advance widths in 1/1000 em, and natural line height in em, per face. Widths only, no font data.', faces: {} };
for (const [face, file] of Object.entries(FACES)) {
  const p = DIRS.map((d) => path.join(d, file)).find((f) => fs.existsSync(f));
  if (!p) { console.warn('not found: ' + file + ' (' + face + ')'); continue; }
  out.faces[face] = parse(fs.readFileSync(p));
  console.log(face.padEnd(20) + Object.keys(out.faces[face].w).length + ' chars, line ' + out.faces[face].line + ' em');
}
fs.writeFileSync(path.join(ROOT, 'rules/font_metrics.json'), JSON.stringify(out) + '\n');
console.log('wrote rules/font_metrics.json');
